/**
 * Loyverse POS -> the envelope.
 *
 * The `normalize` half of the connector unit (specification 13.3). It turns receipts into
 * `EnvelopeRow`s; it does not fetch.
 *
 * ================================================================================================
 * THE SHARPEST CONSTRAINT IN THIS FILE: TWO METRICS, AND NO DICTIONARY CHANGE.
 * ================================================================================================
 *
 * `58-plan-reconciliation.md` section 2.2 worked out what a Loyverse cafe's takings can be
 * expressed as with ZERO changes to `packages/contract/src/metrics.ts`, and the answer is exactly
 * two entries: `revenue` (the money) and `orders` (the count of receipts). That is the whole
 * mapping below, and everything the plan's cafe screens additionally show is deliberately absent:
 *
 *   AVERAGE TICKET   is not a metric and must never become one. It is `revenue / orders`, computed
 *                    AT READ, exactly as `ctr` is clicks over impressions -- and `metrics.ts` says
 *                    in so many words that `ctr` "stays out for that reason". Storing a quotient
 *                    would also store a rounding, and then a week's average ticket would be the
 *                    mean of seven means rather than the week's money over the week's orders. Those
 *                    are different numbers and the second one is the one a cafe owner means.
 *   MARGIN           needs `cost_of_goods`. The data is right here -- line items carry `cost` and
 *                    `cost_total`, and the redaction keep-list preserves both for the day it is
 *                    wanted -- but the COLUMN does not exist, and a currency metric additionally
 *                    requires the fx-constraint guard fix first (build order 1.3 and 4.3).
 *   COVERS,          are not available from Loyverse AT ALL. A grep of the whole OpenAPI document
 *   SPEND PER HEAD   finds no guest, cover, table or pax field; the only related thing is a
 *                    free-text `dining_option`, which is kept in the archive and must never be
 *                    counted as people (section 1.6).
 *   AFTER FEES       has nothing to deduct for a Loyverse-only cafe: there is no delivery platform
 *                    in this connector taking a cut. The honest v1 brief says "takings".
 *   HOURLY TAKINGS   is a GRAIN problem, not a metric problem. `dimensions.date` is a calendar day
 *                    and the upsert key carries no time component, so there is nowhere to put it.
 *   CASH VARIANCE    (`expected_cash` vs `actual_cash` on `/shifts`) is, by section 2.2's own
 *                    reckoning, the best "anything unusual" signal in the whole Loyverse surface --
 *                    and no metric in the dictionary holds it. That is why `SHIFTS_READ` is not
 *                    among the scopes requested: see `PROVIDERS.loyverse` in @repo/oauth.
 *
 * Each of those is a dictionary change, a constraint fix or data that does not exist. Smuggling one
 * in through a connector is exactly what 13.3 rule 2 forbids, and it would make both changes
 * unreviewable at once.
 *
 * ================================================================================================
 * THE TRAPS, IN THE ORDER THEY WOULD BITE.
 * ================================================================================================
 *
 * TRAP 1. A REFUND'S `total_money` IS POSITIVE. The field's own description reads "The total money
 * amount paid by customer (OR RETURNED TO CUSTOMER IN CASE OF REFUND)", and the specification's own
 * worked refund example carries `receipt_type: REFUND` with `total_money: 17.52` -- positive. Add
 * it and a refunded day reads HIGHER than a clean one. So a refund's contribution is negated here,
 * and the sign comes from `receipt_type` rather than from the number's own sign.
 *
 * TRAP 2. A REFUND IS A SECOND RECEIPT, NOT A MUTATION OF THE FIRST. `POST
 * /receipts/{receipt_number}/refund` returns a NEW receipt whose `refund_for` names the sale. So
 * the sale row and the refund row are two envelope rows with two entity ids, and the day's takings
 * are their sum. Trying to net them into the original row would need the original, which this
 * normaliser may not have in the same page -- or in the same run.
 *
 * TRAP 3. `receipt_date` IS NOT `created_at`, AND THE PLATFORM SAYS WHICH IS WHICH. `created_at` is
 * "the autogenerated date and time when the receipt was created in Loyverse"; `receipt_date` is
 * documented as matching it BY DEFAULT and settable to "the date and time in the past when the
 * receipt was created in another system". So `receipt_date` is when the sale happened and
 * `created_at` is when Loyverse heard about it -- which differ for any till that was offline, or
 * for receipts imported from another POS. The sale's day is the one a cafe owner means, so
 * `receipt_date` wins and `created_at` is the fallback. That fallback is the PLATFORM'S OWN rule
 * ("by default, it matches"), not this file's guess.
 *
 * TRAP 4. EVERY TIMESTAMP IS UTC AND THE MERCHANT IS NOT. "All dates and times in the API are in
 * UTC." A 19:00 UTC receipt is 02:00 the NEXT DAY in Bangkok. Which calendar day it belongs to is a
 * question only the merchant's own zone can answer, so `timezone` is required rather than defaulted
 * -- and the suite runs in Asia/Bangkok (see `vitest.config.ts`) because in UTC the right answer
 * and the wrong one are the same string.
 *
 * TRAP 5. A CANCELLED SALE IS ZERO, NOT ABSENT. `cancelled_at` voids a receipt that was already
 * rung and may already have been counted by an earlier run. Emitting no metrics would leave the
 * previous row's value in place through the upsert, so the cancellation would never take effect.
 * Zero is a measurement -- "this receipt is worth nothing now" -- and it is the correct one.
 */

import { type EnvelopeRow, type MetricName, isProvisional, restatesUntil } from "@repo/contract";

/** What the platform calls this object, carried honestly beside our `order` grain. */
export const LOYVERSE_NATIVE_ENTITY_TYPE = "receipt";

/** The enum, verbatim from the `Receipt` schema. */
export const LOYVERSE_RECEIPT_TYPES = ["SALE", "REFUND"] as const;

export type LoyverseReceiptType = (typeof LOYVERSE_RECEIPT_TYPES)[number];

/**
 * ONLY WHAT THE NORMALISER READS.
 *
 * A real receipt carries far more -- line items, payments, taxes, a customer id, loyalty points,
 * card details. Naming those here would invite a reader to think this file consumes them, and the
 * archive's keep-list (`REDACTION_POLICIES.loyverse`) is the thing that has an opinion about them.
 * `fixtures.ts` re-opens the type for exactly that reason.
 */
export interface LoyverseReceipt {
  readonly receipt_number?: string;
  readonly receipt_type?: string;
  readonly refund_for?: string | null;
  readonly created_at?: string;
  readonly receipt_date?: string;
  readonly updated_at?: string;
  readonly cancelled_at?: string | null;
  readonly total_money?: number;
  readonly store_id?: string;
  readonly source?: string;
}

export type LoyverseNormalizeErrorCode =
  | "missing_receipt_number"
  | "missing_date"
  | "unparseable_date"
  | "unknown_receipt_type"
  | "unparseable_value"
  | "missing_currency"
  | "invalid_timezone";

export class LoyverseNormalizeError extends Error {
  constructor(
    message: string,
    readonly code: LoyverseNormalizeErrorCode,
  ) {
    super(message);
    this.name = "LoyverseNormalizeError";
  }
}

/**
 * Refuse a zone before a whole account's rows are labelled with it.
 *
 * Exported so the backfill can call it BEFORE its first request, which is the point: the normaliser
 * would refuse the same value one page later, by which time the merchant's account has already paid
 * for the request and the message names a receipt instead of the connection.
 */
export function assertLoyverseTimezone(timezone: string): void {
  if (timezone.trim() === "") {
    throw new LoyverseNormalizeError(
      "loyverse: no timezone. Every envelope row carries one and there is no default -- Loyverse " +
        "reports every timestamp in UTC, and which day a 19:00 UTC receipt belongs to is a " +
        "question only the merchant's own zone can answer.",
      "invalid_timezone",
    );
  }
  dayFormatter(timezone);
}

const dayFormatters = new Map<string, Intl.DateTimeFormat>();

function dayFormatter(timezone: string): Intl.DateTimeFormat {
  const cached = dayFormatters.get(timezone);
  if (cached !== undefined) return cached;

  let made: Intl.DateTimeFormat;
  try {
    made = new Intl.DateTimeFormat("en-US", {
      timeZone: timezone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    });
  } catch {
    throw new LoyverseNormalizeError(
      `loyverse: ${JSON.stringify(timezone)} is not a timezone this runtime knows. Every date on ` +
        "every row from this account would be labelled with it.",
      "invalid_timezone",
    );
  }
  dayFormatters.set(timezone, made);
  return made;
}

/**
 * A Loyverse UTC instant -> the calendar day it falls on IN THE MERCHANT'S ZONE.
 *
 * TRAP 4 LIVES HERE. A designator is REQUIRED rather than assumed: Loyverse documents UTC and its
 * examples end in `Z`, so a value without one is not a Loyverse timestamp, and reading it as the
 * runtime's local time would move the day by the runner's offset. `wooGmtToDate` faces the mirror
 * image of this problem -- WooCommerce sends designator-less strings that ARE GMT, so it appends a
 * `Z`; here a missing designator means something is wrong, so it refuses.
 */
export function loyverseInstantToDate(
  value: string | undefined,
  field: string,
  timezone: string,
): string {
  if (value === undefined || value.trim() === "") {
    throw new LoyverseNormalizeError(`loyverse: ${field} is missing`, "missing_date");
  }
  if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[Zz]|[+-]\d{2}:\d{2})$/.test(value)) {
    throw new LoyverseNormalizeError(
      `loyverse: ${field} is ${JSON.stringify(value)}, which carries no UTC designator. Loyverse ` +
        'documents that "all dates and times in the API are in UTC" and its own examples end in ' +
        "`Z`, so a value without one is not a Loyverse timestamp. Refusing rather than assuming " +
        "the runtime's offset.",
      "unparseable_date",
    );
  }
  const ms = Date.parse(value);
  if (Number.isNaN(ms)) {
    throw new LoyverseNormalizeError(
      `loyverse: ${field} is ${JSON.stringify(value)}, which is not an instant that exists.`,
      "unparseable_date",
    );
  }

  const parts = dayFormatter(timezone).formatToParts(new Date(ms));
  const part = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((entry) => entry.type === type)?.value;
  const year = part("year");
  const month = part("month");
  const day = part("day");
  if (year === undefined || month === undefined || day === undefined) {
    throw new LoyverseNormalizeError(
      `loyverse: could not read a calendar date for ${field} in ${JSON.stringify(timezone)}`,
      "unparseable_date",
    );
  }
  return `${year}-${month}-${day}`;
}

/**
 * The receipt's type, or a refusal.
 *
 * NOT DEFAULTED TO `SALE`, and the reason is the sign. Counting an unknown document as a sale ADDS
 * its money to the day's takings; counting it as a refund SUBTRACTS it. Both are guesses about the
 * merchant's own money, and a guess that lands in a headline figure is worse than a failed run.
 */
export function receiptTypeOf(receipt: LoyverseReceipt, label: string): LoyverseReceiptType {
  const type = receipt.receipt_type;
  if (type === "SALE" || type === "REFUND") return type;
  throw new LoyverseNormalizeError(
    `loyverse: ${label} has receipt_type ${JSON.stringify(type)}, which is neither SALE nor ` +
      "REFUND. Refusing rather than guessing: counting an unknown document as a sale adds its " +
      "money to the day's takings and counting it as a refund subtracts it, and both are guesses " +
      "about the merchant's own money.",
    "unknown_receipt_type",
  );
}

/**
 * A money field, or a refusal.
 *
 * NOT COERCED TO ZERO. A wrong zero is indistinguishable from a real one in every chart it ever
 * reaches -- and a comped coffee is a real zero, so the two genuinely occur side by side.
 */
export function parseLoyverseMoney(value: number | undefined, field: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new LoyverseNormalizeError(
      `loyverse: ${field} is ${JSON.stringify(value)}, which is not a finite number. Refusing ` +
        "rather than coercing to zero, because a wrong zero is indistinguishable from a real one " +
        "-- and a comped coffee is a real zero.",
      "unparseable_value",
    );
  }
  return value;
}

/**
 * What this receipt contributes to the day's takings. Traps 1 and 5, in one place.
 *
 * `-Math.abs(total)` rather than `-total`, because the sign must come from `receipt_type` and not
 * from the number. The specification's own refund example is positive; if a future response ever
 * sent a refund pre-negated, negating it again would silently turn a refund into a sale.
 */
export function receiptRevenue(receipt: LoyverseReceipt, label: string): number {
  // TRAP 5, checked BEFORE the money is parsed: a cancelled receipt is worth nothing regardless of
  // what `total_money` still says, and refusing it for an unparseable total would fail a run over a
  // field whose value is not being used.
  if (receipt.cancelled_at !== undefined && receipt.cancelled_at !== null) return 0;

  const total = parseLoyverseMoney(receipt.total_money, `${label} total_money`);
  const type = receiptTypeOf(receipt, label);
  return type === "REFUND" ? -Math.abs(total) : total;
}

export interface LoyverseNormalizeOptions {
  readonly receipts: readonly LoyverseReceipt[];
  /**
   * The merchant id from `GET /merchant/`. The account this row belongs to, and half of the
   * envelope's upsert key.
   */
  readonly merchantId: string;
  /**
   * ISO 4217, from `GET /merchant/`'s `currency.code`. REQUIRED, because a receipt carries none and
   * there is no second source to fall back to: see `fetchMerchant`.
   */
  readonly currency: string;
  /**
   * IANA zone the merchant trades in. REQUIRED, and not merely a label: `dimensions.date` is
   * COMPUTED in it. It comes from `public.connections.timezone`, whose null means nobody has told
   * us -- which the backfill refuses to run against rather than assuming UTC.
   */
  readonly timezone: string;
  /** RFC3339. When this pull happened. */
  readonly fetchedAt: string;
  /** RFC3339. Immutable per row; see @repo/contract's restatement note. */
  readonly firstSeenAt: string;
}

/**
 * A page of receipts -> envelope rows, ONE ROW PER RECEIPT.
 *
 * NOT ONE ROW PER DAY, though the envelope's grain is a day. A receipt is the `order` grain 11A.14
 * added, and per-receipt rows are what make a restatement addressable: when a sale is cancelled or
 * refunded, the `updated_at` walk resurfaces THAT receipt, and the upsert key finds exactly the row
 * it corrects. Pre-aggregating to a day would leave nothing to correct -- the day's total would
 * have to be recomputed from receipts the run no longer holds.
 */
export function normalizeLoyverseReceipts(options: LoyverseNormalizeOptions): EnvelopeRow[] {
  if (!/^[A-Za-z]{3}$/.test(options.currency)) {
    throw new LoyverseNormalizeError(
      `loyverse: the currency is ${JSON.stringify(options.currency)}, which is not an ISO 4217 ` +
        "code. Every monetary value on every row from this account would be labelled with it.",
      "missing_currency",
    );
  }
  assertLoyverseTimezone(options.timezone);

  const rows: EnvelopeRow[] = [];

  for (const receipt of options.receipts) {
    const number = receipt.receipt_number;
    if (number === undefined || number === "") {
      throw new LoyverseNormalizeError(
        "loyverse: a receipt carries no receipt_number. Every envelope row is keyed on an entity " +
          "id, so without one a restatement could not find the row it corrects -- and a receipt " +
          "with no id would be re-inserted as a new row on every single pull.",
        "missing_receipt_number",
      );
    }
    const label = `receipt ${number}`;

    // TRAP 3. The sale's own time, falling back to Loyverse's default for it.
    const date = loyverseInstantToDate(
      receipt.receipt_date ?? receipt.created_at,
      `${label} receipt_date`,
      options.timezone,
    );

    const cancelled = receipt.cancelled_at !== undefined && receipt.cancelled_at !== null;
    const type = receiptTypeOf(receipt, label);

    // THE ENTIRE METRIC MAPPING. See the head of this file for the five things deliberately absent.
    const metrics: Partial<Record<MetricName, number>> = {
      // ZERO RATHER THAN ABSENT for a refund or a cancellation, and this is trap 5's other half. A
      // refund receipt is not an order -- counting it would double the day's order count and halve
      // its average ticket -- but it is a MEASURED zero, not an unknown. Absent would let a
      // previous run's value survive the upsert, so the cancellation would never land.
      orders: type === "SALE" && !cancelled ? 1 : 0,
      revenue: receiptRevenue(receipt, label),
    };

    const restates = restatesUntil({
      source: "loyverse",
      date,
      firstSeenAt: options.firstSeenAt,
    });

    rows.push({
      source: "loyverse",
      entity: {
        // `order`, not a new grain. A receipt IS the commerce grain 11A.14 added, and inventing a
        // `receipt` entity type would fork the vocabulary for a synonym. The platform's own word
        // is carried in `native_entity_type` instead, which is what that field is for.
        type: "order",
        // Namespaced like WooCommerce's `wc_` prefix. A Loyverse receipt number is "1-1002" --
        // per-account, not global -- so the prefix is what keeps it from colliding with another
        // source's id in anything that keys on entity id alone.
        id: `lv_${number}`,
        account_id: options.merchantId,
        native_entity_type: LOYVERSE_NATIVE_ENTITY_TYPE,
        native_id: number,
        // The branch. Already on the receipt, so it costs no `STORES_READ` scope to carry -- and
        // it is what lets a two-shop owner see which shop a row came from.
        ...(receipt.store_id === undefined ? {} : { parent_id: receipt.store_id }),
      },
      dimensions: {
        date,
        currency: options.currency.toUpperCase(),
        timezone: options.timezone,
        // NULL, AND THE ENVELOPE PERMITS IT ONLY BECAUSE THIS IS AN `order` ENTITY. The second
        // refusal in `envelopeRowSchema` rejects a commerce metric on an ADVERTISING entity with no
        // window. A till receipt is attributed to nothing -- there is no ad platform anywhere in
        // this connector -- so a window here would be a label with nothing to label.
        attribution_window: null,
      },
      metrics,
      fetched_at: options.fetchedAt,
      // Loyverse publishes a per-row last-modified, and it is the field the incremental pull filters
      // on. Reporting it is what lets a reader see that a row MOVED, and it is how a cancellation
      // reads as a restatement rather than as an unexplained change of value.
      source_updated_at: receipt.updated_at ?? null,
      restates_until: restates,
      is_provisional: isProvisional(restates, new Date(options.fetchedAt)),
      first_seen_at: options.firstSeenAt,
      // The merchant's account has ONE currency and Loyverse converts nothing: there is no
      // multi-currency till here, so there is no rate and no provenance to record.
      fx_source: null,
      fx_rate_date: null,
      fx_rate: null,
      fx_base: null,
      raw: receipt,
    });
  }

  return rows;
}
